import banner from "@/assets/images/banner.png";
import { diaryDataMock } from "./diaryData";
import { galleryDataMock } from "./galleryData";
import { ticketDataMock } from "./ticketData";
import { repostDataMock } from "./repostData";

export const archiveDataMock = [
  {
    archiveId: 1,
    userId: 1,
    title: "나의 첫 아카이브",
    bannerUrl: banner,
    image: "https://picsum.photos/201/300",
    viewCount: 150,
    likeCount: 42,
    visibility: "PUBLIC",
    createdAt: "2025-01-01T00:00:00.000Z",
    lastModifiedAt: "KST Datetime",
    ownerNickname: "홍길동",
    badge: "덕카이브",
    liked: false,
    Diary: diaryDataMock.filter((diary) => diary.archiveId === 1) ?? [],
    Gallery: galleryDataMock.filter((gallery) => gallery.archiveId === 1) ?? [],
    Ticket: ticketDataMock.filter((ticket) => ticket.archiveId === 1) ?? [],
    Repost: repostDataMock.filter((repost) => repost.archiveId === 1) ?? [],
  },
  {
    archiveId: 2,
    userId: 1,
    title: "나의 두번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200",
    image: "https://picsum.photos/202/300",
    viewCount: 150,
    likeCount: 41,
    visibility: "PUBLIC",
    createdAt: "2025-01-01T00:00:00.000Z",
    lastModifiedAt: "KST Datetime",
    ownerNickname: "홍길동",
    badge: "덕카이브",
    liked: false,
    Diary: diaryDataMock.filter((diary) => diary.archiveId === 2) ?? [],
    Gallery: galleryDataMock.filter((gallery) => gallery.archiveId === 2) ?? [],
    Ticket: ticketDataMock.filter((ticket) => ticket.archiveId === 2) ?? [],
    Repost: repostDataMock.filter((repost) => repost.archiveId === 2) ?? [],
  },
  {
    archiveId: 3,
    userId: 1,
    title: "나의 세번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200",
    image: "https://picsum.photos/203/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "PRIVATE",
    createdAt: "2025-01-01T00:00:00.000Z",
    lastModifiedAt: "KST Datetime",
    ownerNickname: "홍길동",
    badge: "덕카이브",
    liked: false,
    Diary: diaryDataMock.filter((diary) => diary.archiveId === 3) ?? [],
    Gallery: galleryDataMock.filter((gallery) => gallery.archiveId === 3) ?? [],
    Ticket: ticketDataMock.filter((ticket) => ticket.archiveId === 3) ?? [],
    Repost: repostDataMock.filter((repost) => repost.archiveId === 3) ?? [],
  },
  {
    archiveId: 4,
    userId: 1,
    title: "나의 네번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200",
    image: "https://picsum.photos/204/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "RESTRICTED",
    createdAt: "2025-01-01T00:00:00.000Z",
    lastModifiedAt: "KST Datetime",
    ownerNickname: "홍길동",
    badge: "덕카이브",
    liked: false,
    Diary: diaryDataMock.filter((diary) => diary.archiveId === 4) ?? [],
    Gallery: galleryDataMock.filter((gallery) => gallery.archiveId === 4) ?? [],
    Ticket: ticketDataMock.filter((ticket) => ticket.archiveId === 4) ?? [],
    Repost: repostDataMock.filter((repost) => repost.archiveId === 4) ?? [],
  },
  {
    archiveId: 5,
    userId: 1,
    title: "나의 다섯번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200",
    image: "https://picsum.photos/205/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "RESTRICTED",
    createdAt: "2025-01-01T00:00:00.000Z",
    lastModifiedAt: "KST Datetime",
    ownerNickname: "홍길동",
    badge: "덕카이브",
    liked: false,
    Diary: diaryDataMock.filter((diary) => diary.archiveId === 5) ?? [],
    Gallery: galleryDataMock.filter((gallery) => gallery.archiveId === 5) ?? [],
    Ticket: ticketDataMock.filter((ticket) => ticket.archiveId === 5) ?? [],
    Repost: repostDataMock.filter((repost) => repost.archiveId === 5) ?? [],
  },
  {
    archiveId: 6,
    userId: 2,
    title: "나의 여섯번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200",
    image: "https://picsum.photos/206/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "PRIVATE",
    createdAt: "2025-01-01T00:00:00.000Z",
    lastModifiedAt: "KST Datetime",
    ownerNickname: "홍길동",
    badge: "덕카이브",
    liked: false,
    Diary: diaryDataMock.filter((diary) => diary.archiveId === 6) ?? [],
    Gallery: galleryDataMock.filter((gallery) => gallery.archiveId === 6) ?? [],
    Ticket: ticketDataMock.filter((ticket) => ticket.archiveId === 6) ?? [],
    Repost: repostDataMock.filter((repost) => repost.archiveId === 6) ?? [],
  },
  {
    archiveId: 7,
    userId: 2,
    title: "나의 일곱번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200",
    image: "https://picsum.photos/207/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "PRIVATE",
    createdAt: "2025-01-01T00:00:00.000Z",
    lastModifiedAt: "KST Datetime",
    ownerNickname: "홍길동",
    badge: "덕카이브",
    liked: false,
    Diary: diaryDataMock.filter((diary) => diary.archiveId === 7) ?? [],
    Gallery: galleryDataMock.filter((gallery) => gallery.archiveId === 7) ?? [],
    Ticket: ticketDataMock.filter((ticket) => ticket.archiveId === 7) ?? [],
    Repost: repostDataMock.filter((repost) => repost.archiveId === 7) ?? [],
  },
  {
    archiveId: 8,
    userId: 2,
    title: "나의 여덟번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200",
    image: "https://picsum.photos/208/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "PRIVATE",
    createdAt: "2025-01-01T00:00:00.000Z",
    lastModifiedAt: "KST Datetime",
    liked: false,
    Diary: diaryDataMock.filter((diary) => diary.archiveId === 8) ?? [],
    Gallery: galleryDataMock.filter((gallery) => gallery.archiveId === 8) ?? [],
    Ticket: ticketDataMock.filter((ticket) => ticket.archiveId === 8) ?? [],
    Repost: repostDataMock.filter((repost) => repost.archiveId === 8) ?? [],
  },
  {
    archiveId: 9,
    userId: 2,
    title: "나의 아홉번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200",
    image: "https://picsum.photos/209/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "PRIVATE",
    createdAt: "2025-01-01T00:00:00.000Z",
    lastModifiedAt: "KST Datetime",
    ownerNickname: "홍길동",
    badge: "덕카이브",
    liked: false,
    Diary: diaryDataMock.filter((diary) => diary.archiveId === 9) ?? [],
    Gallery: galleryDataMock.filter((gallery) => gallery.archiveId === 9) ?? [],
    Ticket: ticketDataMock.filter((ticket) => ticket.archiveId === 9) ?? [],
    Repost: repostDataMock.filter((repost) => repost.archiveId === 9) ?? [],
  },
  {
    archiveId: 10,
    userId: 1,
    title: "나의 열번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200",
    image: "https://picsum.photos/210/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "PRIVATE",
    createdAt: "2025-01-01T00:00:00.000Z",
    lastModifiedAt: "KST Datetime",
    ownerNickname: "홍길동",
    badge: "덕카이브",
    liked: false,
    Diary: diaryDataMock.filter((diary) => diary.archiveId === 10) ?? [],
    Gallery:
      galleryDataMock.filter((gallery) => gallery.archiveId === 10) ?? [],
    Ticket: ticketDataMock.filter((ticket) => ticket.archiveId === 10) ?? [],
    Repost: repostDataMock.filter((repost) => repost.archiveId === 10) ?? [],
  },
  {
    archiveId: 11,
    userId: 1,
    title: "나의 열한번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200",
    image: "https://picsum.photos/211/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "PRIVATE",
    ownerNickname: "홍길동",
    badge: "덕카이브",
    createdAt: "2025-01-01T00:00:00.000Z",
    lastModifiedAt: "KST Datetime",
    liked: false,
    Diary: diaryDataMock.filter((diary) => diary.archiveId === 11) ?? [],
    Gallery:
      galleryDataMock.filter((gallery) => gallery.archiveId === 11) ?? [],
    Ticket: ticketDataMock.filter((ticket) => ticket.archiveId === 11) ?? [],
    Repost: repostDataMock.filter((repost) => repost.archiveId === 11) ?? [],
  },
];
