import banner from "@/assets/images/banner.png";

export const archiveDataMock = [
  {
    archiveId: 1,
    userId: 1,
    title: "나의 첫 아카이브",
    bannerUrl: banner,
    image: "https://picsum.photos/201/300",
    viewCount: 150,
    likeCount: 42,
    visibility: "PUBLIC",
    createdAt: "KST Datetime",
    lastModifiedAt: "KST Datetime",
    ownerNickname: "홍길동",
  },
  {
    archiveId: 2,
    userId: 1,
    title: "나의 두번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200?random=2",
    image: "https://picsum.photos/202/300",
    viewCount: 150,
    likeCount: 41,
    visibility: "PUBLIC",
    createdAt: "KST Datetime",
    lastModifiedAt: "KST Datetime",
  },
  {
    archiveId: 3,
    userId: 1,
    title: "나의 세번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200?random=3",
    image: "https://picsum.photos/203/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "PRIVATE",
    createdAt: "KST Datetime",
    lastModifiedAt: "KST Datetime",
  },
  {
    archiveId: 4,
    userId: 1,
    title: "나의 네번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200?random=4",
    image: "https://picsum.photos/204/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "RESTRICTED",
    createdAt: "KST Datetime",
    lastModifiedAt: "KST Datetime",
  },
  {
    archiveId: 5,
    userId: 1,
    title: "나의 다섯번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200?random=5",
    image: "https://picsum.photos/205/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "RESTRICTED",
    createdAt: "KST Datetime",
    lastModifiedAt: "KST Datetime",
  },
  {
    archiveId: 6,
    userId: 2,
    title: "나의 여섯번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200?random=6",
    image: "https://picsum.photos/206/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "PRIVATE",
    createdAt: "KST Datetime",
    lastModifiedAt: "KST Datetime",
  },
  {
    archiveId: 7,
    userId: 2,
    title: "나의 일곱번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200?random=7",
    image: "https://picsum.photos/207/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "PRIVATE",
    createdAt: "KST Datetime",
    lastModifiedAt: "KST Datetime",
  },
  {
    archiveId: 8,
    userId: 2,
    title: "나의 여덟번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200?random=8",
    image: "https://picsum.photos/208/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "PRIVATE",
    createdAt: "KST Datetime",
    lastModifiedAt: "KST Datetime",
  },
  {
    archiveId: 9,
    userId: 2,
    title: "나의 아홉번째 아카이브",
    bannerUrl: "https://picsum.photos/1920/200?random=9",
    image: "https://picsum.photos/209/300",
    viewCount: 150,
    likeCount: 50,
    visibility: "PRIVATE",
    createdAt: "KST Datetime",
    lastModifiedAt: "KST Datetime",
  },
];
